### ISSUE TITLE
First milestone

### ISSUE THREAD

**Issue by koenw** [paritytech/bankbot#1]
* [x] Github PR comment listener
  * [x] Github webhook secret authentication
  * [ ] Whitelist of allowed repositories (everything under *paritytech*?)
  * [ ] User authorization (should be part of the org in order to run it)
* [x] Shared incoming job queue
  * [x] Long-polling
  * [x] Exponential backoff
  * [ ] Authentication
  * [ ] Peer discovery through DNS SRV records
* [ ] Job execution
  * [x] Checkout & prepare git repository
  * [x] Load rhai script from repository
  * [x] Run script
    * [ ] Pass extra arguments to script
    * [ ] Provide API to commit/push any output files
    * [x] Provide API to run cargo
    * [ ] Provide API to comment on issue
    * [ ] Use Linux Namespaces (e.g. using [*unshare*](https://github.com/tailhook/unshare)) to isolate the script and cargo from the rest of the system
* [x] Runtime configuration
  * [x] Command-line and environment variable configuration
    * [x] Github webhook secret
    * [x] Listen address & port
    * [x] Log-level (debug,info,warn,error)
    * [x] repository root directory
    * [x] bot command prefix (e.g. `/bench-bot`)
    * [ ] DNS SRV Record Name (e.g. *benchbot.opstooling.parity.io*)
  * [x] Command-line `--help` option
